#!/usr/bin/env bash
# Spinny Local Node — Ubuntu auto-installer
# Usage: bash install.sh
# Installs Node.js 22, Ollama, the node itself, and registers a systemd service.
set -e

REPO_URL="https://github.com/spinny-au/spinny-local-minimal.git"
INSTALL_DIR="$HOME/.spinny/node"
SERVICE_NAME="spinny-local"
NODE_PORT=47821

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

step() { echo -e "\n${CYAN}${BOLD}▶ $1${RESET}"; }
ok()   { echo -e "${GREEN}✓ $1${RESET}"; }
warn() { echo -e "${RED}⚠ $1${RESET}"; }

require_root_or_sudo() {
  if [[ $EUID -ne 0 ]] && ! sudo -n true 2>/dev/null; then
    echo "This installer needs sudo access to install system packages."
    sudo -v
  fi
}

# ── 1. Node.js 22 ─────────────────────────────────────────────────────────────
step "Checking Node.js"
if node --version 2>/dev/null | grep -q "^v2[2-9]"; then
  ok "Node.js $(node --version) already installed"
else
  step "Installing Node.js 22 via NodeSource"
  require_root_or_sudo
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  sudo apt-get install -y nodejs
  ok "Node.js $(node --version) installed"
fi

# ── 2. Ollama ─────────────────────────────────────────────────────────────────
step "Checking Ollama"
if command -v ollama &>/dev/null; then
  ok "Ollama already installed: $(ollama --version 2>/dev/null || echo 'unknown version')"
else
  step "Installing Ollama"
  curl -fsSL https://ollama.com/install.sh | sh
  ok "Ollama installed"
fi

# Ensure Ollama is running
if ! systemctl is-active --quiet ollama 2>/dev/null; then
  step "Starting Ollama service"
  sudo systemctl enable ollama --now 2>/dev/null || ollama serve &>/dev/null &
  sleep 2
fi

# List already-installed models
MODELS=$(ollama list 2>/dev/null | tail -n +2 | awk '{print $1}' | grep -v '^$' || true)
if [[ -n "$MODELS" ]]; then
  ok "Ollama models already installed:"
  echo "$MODELS" | sed 's/^/    /'
else
  echo -e "  No Ollama models installed yet. Pull one later with: ollama pull llama3.2:3b"
fi

# ── 3. Tailscale (detect, don't auto-install) ─────────────────────────────────
step "Checking Tailscale"
if command -v tailscale &>/dev/null; then
  TS_IP=$(tailscale ip --4 2>/dev/null || true)
  if [[ -n "$TS_IP" ]]; then
    ok "Tailscale active — node will be reachable at ${BOLD}${TS_IP}:${NODE_PORT}${RESET}"
  else
    warn "Tailscale installed but not connected. Run: sudo tailscale up"
    TS_IP=""
  fi
else
  echo "  Tailscale not installed. For remote access from other devices, install it:"
  echo "    curl -fsSL https://tailscale.com/install.sh | sh"
  echo "    sudo tailscale up"
  TS_IP=""
fi

# ── 4. Clone / update the node ────────────────────────────────────────────────
step "Setting up Spinny local node in $INSTALL_DIR"
mkdir -p "$(dirname "$INSTALL_DIR")"
if [[ -d "$INSTALL_DIR/.git" ]]; then
  git -C "$INSTALL_DIR" pull --ff-only
  ok "Updated to latest"
else
  git clone "$REPO_URL" "$INSTALL_DIR"
  ok "Cloned"
fi

step "Installing npm dependencies"
npm install --prefix "$INSTALL_DIR" --omit=dev --silent
ok "Dependencies ready"

# ── 5. Environment file ───────────────────────────────────────────────────────
ENV_FILE="$INSTALL_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh
SPINNY_BIND_HOST=0.0.0.0
EOF
  ok "Created .env (bind host: 0.0.0.0)"
else
  # Ensure SPINNY_BIND_HOST is set
  grep -q "SPINNY_BIND_HOST" "$ENV_FILE" || echo "SPINNY_BIND_HOST=0.0.0.0" >> "$ENV_FILE"
  ok ".env already exists — preserved"
fi

# ── 6. systemd service ────────────────────────────────────────────────────────
step "Installing systemd service: $SERVICE_NAME"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

sudo tee "$SERVICE_FILE" > /dev/null <<EOF
[Unit]
Description=Spinny Local Node
After=network-online.target ollama.service
Wants=network-online.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=-$ENV_FILE
ExecStart=$(which node) --experimental-sqlite --no-warnings --env-file-if-exists=.env src/main.js start
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=spinny-local

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"
ok "Service started"

# ── 7. Show pairing info ──────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}Waiting for pairing code...${RESET}"
sleep 4

# Grab the pairing code from journal
CODE=$(journalctl -u "$SERVICE_NAME" --no-pager -n 50 2>/dev/null \
  | grep -oE 'Pairing code:[[:space:]]+[A-Z0-9]{6}' \
  | tail -1 \
  | grep -oE '[A-Z0-9]{6}' || true)

NODE_ADDR="${TS_IP:+${TS_IP}:${NODE_PORT}}"
NODE_ADDR="${NODE_ADDR:-localhost:${NODE_PORT}}"

echo ""
echo -e "╔══════════════════════════════════════════════════╗"
if [[ -n "$CODE" ]]; then
  printf "║  Pairing code:  %-33s║\n" "$CODE"
else
  printf "║  Pairing code:  %-33s║\n" "(check: journalctl -u spinny-local -f)"
fi
printf   "║  Node address:  %-33s║\n" "$NODE_ADDR"
echo -e  "╠══════════════════════════════════════════════════╣"
echo -e  "║  In Spinny → Settings → Local Node:             ║"
echo -e  "║    1. Enter node address (if not localhost)      ║"
echo -e  "║    2. Enter pairing code                         ║"
echo -e  "╚══════════════════════════════════════════════════╝"
echo ""
echo -e "To follow live logs:  ${BOLD}journalctl -u spinny-local -f${RESET}"
echo -e "To check status:      ${BOLD}systemctl status spinny-local${RESET}"
echo ""
