#!/usr/bin/env bash
# Spinny Local Node — macOS installer
#
# One-liner:
#   bash <(curl -fsSL https://raw.githubusercontent.com/spinny-au/spinny-local-minimal/main/scripts/install-macos.sh)
#
# Fresh install (wipes state, re-pairs):
#   bash <(curl -fsSL .../install-macos.sh) --fresh
#
# Update only (keeps pairing):
#   bash <(curl -fsSL .../install-macos.sh) --update
set -euo pipefail

REPO_URL="https://github.com/spinny-au/spinny-local-minimal.git"
INSTALL_DIR="$HOME/.spinny/node"
STATE_DIR="$HOME/.spinny-local"
PLIST_DIR="$HOME/Library/LaunchAgents"
PLIST="$PLIST_DIR/au.spinny.local-node.plist"
SERVICE_LABEL="au.spinny.local-node"
NODE_PORT=47821
CONTROL_URL="https://spinny.au"

FRESH=false; UPDATE=false
for arg in "$@"; do
  [[ "$arg" == "--fresh"  ]] && FRESH=true
  [[ "$arg" == "--update" ]] && UPDATE=true
done

# ── Colours ───────────────────────────────────────────────────────────────────
R='\033[0;31m' G='\033[0;32m' Y='\033[1;33m' C='\033[0;36m'
B='\033[1m' DIM='\033[2m' RST='\033[0m'

step() { echo -e "\n${C}${B}▶ $1${RST}"; }
ok()   { echo -e "${G}✓ $1${RST}"; }
warn() { echo -e "${Y}⚠ $1${RST}"; }
fail() { echo -e "${R}✗ $1${RST}"; exit 1; }

print_rainbow() {
  local line="$1" idx="${2:-0}"
  local cols=(31 33 32 36 34 35)
  local col=${cols[$((idx % 6))]}
  echo -e "\033[1;${col}m${line}\033[0m"
}

# ── 1. Node.js 22 ─────────────────────────────────────────────────────────────
step "Checking Node.js"
if node --version 2>/dev/null | grep -qE '^v2[2-9]'; then
  ok "Node.js $(node --version) already installed"
else
  step "Installing Node.js 22"
  if command -v brew &>/dev/null; then
    brew install node@22 --quiet
    brew link --force --overwrite node@22 2>/dev/null || true
  else
    warn "Homebrew not found — installing Node.js via official installer"
    _pkg=$(mktemp /tmp/node-XXXXXX.pkg)
    curl -fsSL "https://nodejs.org/dist/latest-v22.x/node-v22.0.0.pkg" -o "$_pkg" || \
      { warn "Direct download failed — install Node.js 22 from https://nodejs.org then re-run"; fail "Node.js required"; }
    sudo installer -pkg "$_pkg" -target / >/dev/null
    rm -f "$_pkg"
  fi
  ok "Node.js $(node --version) installed"
fi

# ── 2. Git ────────────────────────────────────────────────────────────────────
step "Checking Git"
if command -v git &>/dev/null; then
  ok "$(git --version)"
else
  warn "Git not found — installing via Xcode Command Line Tools"
  xcode-select --install 2>/dev/null || true
  ok "Git installed"
fi

# ── 3. Ollama ─────────────────────────────────────────────────────────────────
step "Checking Ollama"
OLLAMA_RUNNING=false; OLLAMA_MODELS=()
if command -v ollama &>/dev/null; then
  ok "Ollama already installed"
else
  step "Installing Ollama"
  if command -v brew &>/dev/null; then
    brew install ollama --quiet
  else
    curl -fsSL https://ollama.com/install.sh | sh
  fi
  ok "Ollama installed"
fi

if ollama list &>/dev/null; then
  OLLAMA_RUNNING=true
  while IFS= read -r line; do
    [[ -z "$line" || "$line" == NAME* ]] && continue
    OLLAMA_MODELS+=("$(echo "$line" | awk '{print $1}')")
  done < <(ollama list 2>/dev/null | tail -n +2)
fi

# ── 4. Fresh / Update ─────────────────────────────────────────────────────────
if $FRESH; then
  step "Fresh install — wiping previous installation"
  launchctl unload "$PLIST" 2>/dev/null || true
  pkill -f "spinny-local-minimal/node" 2>/dev/null || true
  rm -rf "$INSTALL_DIR" "$STATE_DIR"
  ok "Wiped"
fi

if $UPDATE && [[ ! -d "$INSTALL_DIR/.git" ]]; then
  fail "No existing install at $INSTALL_DIR — run without --update first"
fi

# ── 5. Clone / pull ───────────────────────────────────────────────────────────
step "Setting up Spinny Local Node"
mkdir -p "$(dirname "$INSTALL_DIR")"
if [[ -d "$INSTALL_DIR/.git" ]]; then
  launchctl unload "$PLIST" 2>/dev/null || true
  git -C "$INSTALL_DIR" pull --ff-only
  ok "Updated to latest"
else
  git clone "$REPO_URL" "$INSTALL_DIR"
  ok "Cloned"
fi

# ── 6. Dependencies ───────────────────────────────────────────────────────────
step "Installing npm dependencies"
npm install --prefix "$INSTALL_DIR" --omit=dev --silent
ok "Dependencies ready"

# ── 7. .env ───────────────────────────────────────────────────────────────────
step "Writing .env"
ENV_FILE="$INSTALL_DIR/.env"
EXISTING_TOKEN=""
[[ -f "$ENV_FILE" ]] && EXISTING_TOKEN=$(grep -oE 'SPINNY_DASHBOARD_TOKEN=\S+' "$ENV_FILE" 2>/dev/null | cut -d= -f2 || true)
DASH_TOKEN="${EXISTING_TOKEN:-$(openssl rand -base64 33 | tr -d '/+=\n' | head -c 44)}"

{
  echo "# Auto-generated by install-macos.sh — do not commit"
  echo "SPINNY_CONTROL_URL=$CONTROL_URL"
  echo "SPINNY_BIND_HOST=0.0.0.0"
  echo "SPINNY_DASHBOARD_TOKEN=${DASH_TOKEN}"
  echo "SPINNY_ALLOW_INSECURE_FILE_KEY=1"
} > "$ENV_FILE"
ok ".env written"

# ── 8. launchd service ────────────────────────────────────────────────────────
step "Installing launchd service"
NODE_BIN=$(which node)
mkdir -p "$PLIST_DIR"
cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${SERVICE_LABEL}</string>
  <key>WorkingDirectory</key><string>${INSTALL_DIR}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
  </dict>
  <key>ProgramArguments</key>
  <array>
    <string>${NODE_BIN}</string>
    <string>--experimental-sqlite</string>
    <string>--no-warnings</string>
    <string>--env-file-if-exists=.env</string>
    <string>src/main.js</string>
    <string>start</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>5</integer>
  <key>StandardOutPath</key><string>${INSTALL_DIR}/spinny-local.log</string>
  <key>StandardErrorPath</key><string>${INSTALL_DIR}/spinny-local.log</string>
</dict>
</plist>
PLIST

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
ok "Service started (runs at login)"

# ── 9. Wait for pairing code ──────────────────────────────────────────────────
step "Waiting for node to initialise"
STATE_FILE="$STATE_DIR/state.json"
PAIRING_CODE=""; PAIRED=false
for i in $(seq 1 30); do
  sleep 1
  [[ ! -f "$STATE_FILE" ]] && continue
  CODE=$(grep -oP '(?<="pairingCode":")[^"]+' "$STATE_FILE" 2>/dev/null || true)
  IS_PAIRED=$(grep -oP '(?<="paired":)true' "$STATE_FILE" 2>/dev/null || true)
  [[ -n "$IS_PAIRED" ]] && PAIRED=true && break
  [[ -n "$CODE" ]] && PAIRING_CODE="$CODE" && break
done
[[ -z "$PAIRING_CODE" && "$PAIRED" == "false" ]] && PAIRING_CODE="run: launchctl log $(SERVICE_LABEL)"

# ── 10. System info ───────────────────────────────────────────────────────────
CPU_COUNT=$(sysctl -n hw.logicalcpu 2>/dev/null || nproc 2>/dev/null || echo '?')
RAM_GB=$(awk "BEGIN {printf \"%.1f GB\", $(sysctl -n hw.memsize 2>/dev/null || echo 0) / 1073741824}")
DISK_FREE=$(df -h "$INSTALL_DIR" 2>/dev/null | awk 'NR==2{print $4}' || echo '?')
GPU_INFO=$(system_profiler SPDisplaysDataType 2>/dev/null | awk -F': ' '/Chipset Model/{print $2; exit}' || echo 'No GPU info')
NODE_VER=$(node -p "require('$INSTALL_DIR/package.json').version" 2>/dev/null || echo '?')
SVC_OK=$(launchctl list "$SERVICE_LABEL" &>/dev/null && echo true || echo false)
STATUS_STR=$( $SVC_OK && echo "● Running" || echo "○ Not running — run: launchctl load $PLIST")
OLLAMA_STR=$($OLLAMA_RUNNING && echo "● Running  •  ${#OLLAMA_MODELS[@]} model(s)" || echo "○ Not running")
BRAIN="${OLLAMA_MODELS[0]:-no model installed yet}"
GIT_STR="✓ $(git --version)  (updates: re-run install-macos.sh)"

PORT_OK=false
curl -sf --max-time 3 "http://localhost:${NODE_PORT}/health" >/dev/null 2>&1 && PORT_OK=true

# ── 11. Banner ────────────────────────────────────────────────────────────────
clear

LOGO=(
'    /$$$$$$  /$$$$$$$  /$$$$$$ /$$   /$$ /$$   /$$ /$$     /$$'
'   /$$__  $$| $$__  $$|_  $$_/| $$$ | $$| $$$ | $$|  $$   $$/ '
'  | $$  \__/| $$  \ $$  | $$  | $$$$| $$| $$$$| $$ \  $$ /$$/ '
'  |  $$$$$$ | $$$$$$$/  | $$  | $$ $$ $$| $$ $$ $$  \  $$$$/ '
'   \____  $$| $$____/   | $$  | $$  $$$$| $$  $$$$   \  $$/ '
'   /$$  \ $$| $$        | $$  | $$\  $$$| $$\  $$$    | $$   '
'  |  $$$$$$/| $$       /$$$$$$| $$ \  $$| $$ \  $$    | $$   '
'   \______/ |__/      |______/|__/  \__/|__/  \__/    |__/  '
)

LINE='===================================================================='

echo ""
echo -e "${Y}${B}  ↓  ↓  ↓  ↓  ↓  ↓  ↓   IMPORTANT — COPY & STORE   ↓  ↓  ↓  ↓  ↓  ↓  ↓${RST}"
echo -e "${DIM}${LINE}${RST}"
for i in "${!LOGO[@]}"; do print_rainbow "${LOGO[$i]}" $i; done
echo -e "${DIM}${LINE}${RST}"
echo -e "  🚀  ${B}SPINNY LOCAL NODE  v${NODE_VER}  SUCCESSFULLY INSTALLED${RST}  🚀"
echo -e "${DIM}--------------------------------------------------------------------${RST}"
echo ""
printf "  %-18s: %s vCPUs  •  %s  •  %s  •  %s free\n" "Hardware"  "$CPU_COUNT" "$RAM_GB" "$GPU_INFO" "$DISK_FREE"
printf "  %-18s: %s\n"                                   "Ollama"    "$OLLAMA_STR"
printf "  %-18s: %s\n"                                   "Brain"     "$BRAIN"
printf "  %-18s: %s\n"                                   "Status"    "$STATUS_STR"
echo ""
printf "  %-18s: http://localhost:%s\n" "Node UI" "$NODE_PORT"
echo ""
if $PAIRED; then
  printf "  %-18s: already paired ✓\n" "Pairing"
else
  printf "  %-18s: %s\n" "Pairing code" "$PAIRING_CODE"
  echo -e "                       ${DIM}Enter this at spinny.au → Settings → Local Node${RST}"
fi
echo ""
printf "  %-18s: " "Dashboard token"
echo -e "${Y}${B}${DASH_TOKEN}${RST}"
echo -e "                       ${DIM}${ENV_FILE}${RST}"
echo ""
printf "  %-18s: %s\n" "Git" "$GIT_STR"
echo ""
echo -e "${DIM}--------------------------------------------------------------------${RST}"
if $PORT_OK; then
  echo -e "  ${G}${B}✓ Port ${NODE_PORT} reachable on localhost${RST}"
else
  echo -e "  ${Y}○ Port ${NODE_PORT} not yet reachable — node is still starting${RST}"
fi
echo -e "${DIM}${LINE}${RST}"
echo -e "  Node is ready. Open ${B}spinny.au${RST} and enter your pairing code."
echo -e "${DIM}${LINE}${RST}"
echo ""
