name = "spinny-local-relay"
main = "worker.js"
compatibility_date = "2026-05-18"
workers_dev = true

routes = [
  { pattern = "relay.spinny.au/*", custom_domain = true }
]

[[durable_objects.bindings]]
name = "NODE_RELAY"
class_name = "NodeRelay"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NodeRelay"]
